getAteco <- function(df){
  
  df$`ateconames`[df$`ATECO10`== "01" ] <- "COLTIVAZIONI AGRICOLE E PRODUZIONE DI PRODOTTI ANIMALI, CACCIA E SERVIZI CONNESSI"
  df$`ateconames`[df$`ATECO10`== "02" ] <-"SILVICOLTURA ED UTILIZZO DI AREE FORESTALI"
  df$`ateconames`[df$`ATECO10`== "03" ] <-"PESCA E ACQUACOLTURA"
  df$`ateconames`[df$`ATECO10`== "05" ] <-"ESTRAZIONE DI CARBONE (ESCLUSA TORBA)"
  df$`ateconames`[df$`ATECO10`== "06" ] <-"ESTRAZIONE DI PETROLIO GREGGIO E DI GAS NATURALE"
  df$`ateconames`[df$`ATECO10`== "07" ] <-"ESTRAZIONE DI MINERALI METALLIFERI"
  df$`ateconames`[df$`ATECO10`== "08" ] <-"ALTRE ATTIVITÀ DI ESTRAZIONE DI MINERALI DA CAVE E MINIERE"
  df$`ateconames`[df$`ATECO10`== "09" ] <-"ATTIVITÀ DEI SERVIZI DI SUPPORTO ALL'ESTRAZIONE"
  df$`ateconames`[df$`ATECO10`== "10" ] <-"INDUSTRIE ALIMENTARI"
  df$`ateconames`[df$`ATECO10`== "11" ] <-"INDUSTRIA DELLE BEVANDE"
  df$`ateconames`[df$`ATECO10`== "13" ] <-"INDUSTRIE TESSILI"
  df$`ateconames`[df$`ATECO10`== "14" ] <-"CONFEZIONE DI ARTICOLI DI ABBIGLIAMENTO; CONFEZIONE DI ARTICOLI IN PELLE E PELLICCIA"
  df$`ateconames`[df$`ATECO10`== "15" ] <-"FABBRICAZIONE DI ARTICOLI IN PELLE E SIMILI"
  df$`ateconames`[df$`ATECO10`== "16" ] <-"INDUSTRIA DEL LEGNO E DEI PRODOTTI IN LEGNO E SUGHERO (ESCLUSI I MOBILI); FABBRICAZIONE DI ARTICOLI IN PAGLIA E MATERIALI DA INTRECCIO"
  df$`ateconames`[df$`ATECO10`== "17" ] <-"FABBRICAZIONE DI CARTA E DI PRODOTTI DI CARTA"
  df$`ateconames`[df$`ATECO10`== "18" ] <-"STAMPA E RIPRODUZIONE DI SUPPORTI REGISTRATI"
  df$`ateconames`[df$`ATECO10`== "19" ] <-"FABBRICAZIONE DI COKE E PRODOTTI DERIVANTI DALLA RAFFINAZIONE DEL PETROLIO"
  df$`ateconames`[df$`ATECO10`== "20" ] <-"FABBRICAZIONE DI PRODOTTI CHIMICI"
  df$`ateconames`[df$`ATECO10`== "21" ] <-"FABBRICAZIONE DI PRODOTTI FARMACEUTICI DI BASE E DI PREPARATI FARMACEUTICI"
  df$`ateconames`[df$`ATECO10`== "22" ] <-"FABBRICAZIONE DI ARTICOLI IN GOMMA E MATERIE PLASTICHE"
  df$`ateconames`[df$`ATECO10`== "23" ] <-"FABBRICAZIONE DI ALTRI PRODOTTI DELLA LAVORAZIONE DI MINERALI NON METALLIFERI"
  df$`ateconames`[df$`ATECO10`== "24" ] <-"METALLURGIA"
  df$`ateconames`[df$`ATECO10`== "25" ] <-"FABBRICAZIONE DI PRODOTTI IN METALLO (ESCLUSI MACCHINARI E ATTREZZATURE)"
  df$`ateconames`[df$`ATECO10`== "26" ] <-"FABBRICAZIONE DI COMPUTER E PRODOTTI DI ELETTRONICA E OTTICA; APPARECCHI ELETTROMEDICALI, APPARECCHI DI MISURAZIONE E DI OROLOGI"
  df$`ateconames`[df$`ATECO10`== "27" ] <-"FABBRICAZIONE DI APPARECCHIATURE ELETTRICHE ED APPARECCHIATURE PER USO DOMESTICO NON ELETTRICHE"
  df$`ateconames`[df$`ATECO10`== "28" ] <-"FABBRICAZIONE DI MACCHINARI ED APPARECCHIATURE NCA"
  df$`ateconames`[df$`ATECO10`== "29" ] <-"FABBRICAZIONE DI AUTOVEICOLI, RIMORCHI E SEMIRIMORCHI"
  df$`ateconames`[df$`ATECO10`== "30" ] <-"FABBRICAZIONE DI ALTRI MEZZI DI TRASPORTO"
  df$`ateconames`[df$`ATECO10`== "31" ] <-"FABBRICAZIONE DI MOBILI"
  df$`ateconames`[df$`ATECO10`== "32" ] <-"ALTRE INDUSTRIE MANIFATTURIERE"
  df$`ateconames`[df$`ATECO10`== "33" ] <-"RIPARAZIONE, MANUTENZIONE ED INSTALLAZIONE DI MACCHINE ED APPARECCHIATURE"
  df$`ateconames`[df$`ATECO10`== "35" ] <-"FORNITURA DI ENERGIA ELETTRICA, GAS, VAPORE E ARIA CONDIZIONATA"
  df$`ateconames`[df$`ATECO10`== "36" ] <-"RACCOLTA, TRATTAMENTO E FORNITURA DI ACQUA"
  df$`ateconames`[df$`ATECO10`== "37" ] <-"GESTIONE DELLE RETI FOGNARIE"
  df$`ateconames`[df$`ATECO10`== "38" ] <-"ATTIVITÀ DI RACCOLTA, TRATTAMENTO E SMALTIMENTO DEI RIFIUTI; RECUPERO DEI MATERIALI"
  df$`ateconames`[df$`ATECO10`== "39" ] <-"ATTIVITÀ DI RISANAMENTO E ALTRI SERVIZI DI GESTIONE DEI RIFIUTI"
  df$`ateconames`[df$`ATECO10`== "40" ] <-""
  df$`ateconames`[df$`ATECO10`== "41" ] <-"COSTRUZIONE DI EDIFICI"
  df$`ateconames`[df$`ATECO10`== "42" ] <-"INGEGNERIA CIVILE"
  df$`ateconames`[df$`ATECO10`== "43" ] <-"LAVORI DI COSTRUZIONE SPECIALIZZATI"
  
  df$`ateconames`[df$`ATECO10`== "45" ] <-"COMMERCIO ALL'INGROSSO E AL DETTAGLIO E RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI"
  df$`ateconames`[df$`ATECO10`== "46" ] <-"COMMERCIO ALL'INGROSSO (ESCLUSO QUELLO DI AUTOVEICOLI E DI MOTOCICLI)"
  df$`ateconames`[df$`ATECO10`== "47" ] <-"COMMERCIO AL DETTAGLIO (ESCLUSO QUELLO DI AUTOVEICOLI E DI MOTOCICLI)"
  
  df$`ateconames`[df$`ATECO10`== "49" ] <-"TRASPORTO TERRESTRE E TRASPORTO MEDIANTE CONDOTTE"
  df$`ateconames`[df$`ATECO10`== "50" ] <-"TRASPORTO MARITTIMO E PER VIE D'ACQUA"
  df$`ateconames`[df$`ATECO10`== "51" ] <-"TRASPORTO AEREO"
  df$`ateconames`[df$`ATECO10`== "52" ] <-"MAGAZZINAGGIO E ATTIVITÀ DI SUPPORTO AI TRASPORTI"
  df$`ateconames`[df$`ATECO10`== "53" ] <-"SERVIZI POSTALI E ATTIVITÀ DI CORRIERE"
  df$`ateconames`[df$`ATECO10`== "54" ] <-""
  df$`ateconames`[df$`ATECO10`== "55" ] <-"ALLOGGIO"
  df$`ateconames`[df$`ATECO10`== "56" ] <-"ATTIVITÀ DEI SERVIZI DI RISTORAZIONE"
  df$`ateconames`[df$`ATECO10`== "58" ] <-"ATTIVITÀ EDITORIALI"
  df$`ateconames`[df$`ATECO10`== "59" ] <-"ATTIVITÀ DI PRODUZIONE CINEMATOGRAFICA, DI VIDEO E DI PROGRAMMI TELEVISIVI, DI REGISTRAZIONI MUSICALI E SONORE"
  df$`ateconames`[df$`ATECO10`== "60" ] <-"ATTIVITÀ DI PROGRAMMAZIONE E TRASMISSIONE"
  df$`ateconames`[df$`ATECO10`== "61" ] <-"TELECOMUNICAZIONI"
  df$`ateconames`[df$`ATECO10`== "62" ] <-"PRODUZIONE DI SOFTWARE, CONSULENZA INFORMATICA E ATTIVITÀ CONNESSE"
  df$`ateconames`[df$`ATECO10`== "63" ] <-"ATTIVITÀ DEI SERVIZI D'INFORMAZIONE E ALTRI SERVIZI INFORMATICI"
  df$`ateconames`[df$`ATECO10`== "64" ] <-"ATTIVITÀ DI SERVIZI FINANZIARI (ESCLUSE LE ASSICURAZIONI E I FONDI PENSIONE)"
  df$`ateconames`[df$`ATECO10`== "65" ] <-"ASSICURAZIONI, RIASSICURAZIONI E FONDI PENSIONE (ESCLUSE LE ASSICURAZIONI SOCIALI OBBLIGATORIE)"
  df$`ateconames`[df$`ATECO10`== "66" ] <-"ATTIVITÀ AUSILIARIE DEI SERVIZI FINANZIARI E DELLE ATTIVITÀ ASSICURATIVE"
  df$`ateconames`[df$`ATECO10`== "67" ] <-""
  df$`ateconames`[df$`ATECO10`== "68" ] <-"ATTIVITÀ IMMOBILIARI"
  df$`ateconames`[df$`ATECO10`== "69" ] <-"ATTIVITÀ LEGALI E CONTABILITÀ"
  df$`ateconames`[df$`ATECO10`== "70" ] <-"ATTIVITÀ DI DIREZIONE AZIENDALE E DI CONSULENZA GESTIONALE"
  df$`ateconames`[df$`ATECO10`== "71" ] <-"ATTIVITÀ DEGLI STUDI DI ARCHITETTURA E D'INGEGNERIA; COLLAUDI ED ANALISI TECNICHE"
  df$`ateconames`[df$`ATECO10`== "72" ] <-"RICERCA SCIENTIFICA E SVILUPPO"
  df$`ateconames`[df$`ATECO10`== "73" ] <-"PUBBLICITÀ E RICERCHE DI MERCATO"
  df$`ateconames`[df$`ATECO10`== "74" ] <-"ALTRE ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE"
  df$`ateconames`[df$`ATECO10`== "75" ] <-"SERVIZI VETERINARI"
  df$`ateconames`[df$`ATECO10`== "76" ] <-""
  df$`ateconames`[df$`ATECO10`== "77" ] <-"ATTIVITÀ DI NOLEGGIO E LEASING OPERATIVO"
  df$`ateconames`[df$`ATECO10`== "78" ] <-"ATTIVITÀ DI RICERCA, SELEZIONE, FORNITURA DI PERSONALE"
  df$`ateconames`[df$`ATECO10`== "79" ] <-"ATTIVITÀ DEI SERVIZI DELLE AGENZIE DI VIAGGIO, DEI TOUR OPERATOR E SERVIZI DI PRENOTAZIONE E ATTIVITÀ CONNESSE"
  df$`ateconames`[df$`ATECO10`== "80" ] <-"SERVIZI DI VIGILANZA E INVESTIGAZIONE"
  df$`ateconames`[df$`ATECO10`== "81" ] <-"ATTIVITÀ DI SERVIZI PER EDIFICI E PAESAGGIO"
  df$`ateconames`[df$`ATECO10`== "82" ] <-"ATTIVITÀ DI SUPPORTO PER LE FUNZIONI D'UFFICIO E ALTRI SERVIZI DI SUPPORTO ALLE IMPRESE"
  df$`ateconames`[df$`ATECO10`== "83" ] <-"SERVIZI DI VIGILANZA E INVESTIGAZIONE"
  df$`ateconames`[df$`ATECO10`== "84" ] <-"AMMINISTRAZIONE PUBBLICA E DIFESA; ASSICURAZIONE SOCIALE OBBLIGATORIA"
  df$`ateconames`[df$`ATECO10`== "85" ] <-"ISTRUZIONE"
  df$`ateconames`[df$`ATECO10`== "86" ] <-"ASSISTENZA SANITARIA"
  df$`ateconames`[df$`ATECO10`== "87" ] <-"SERVIZI DI ASSISTENZA SOCIALE RESIDENZIALE"
  df$`ateconames`[df$`ATECO10`== "88" ] <-"AASSISTENZA SOCIALE NON RESIDENZIALE"
  df$`ateconames`[df$`ATECO10`== "90" ] <-"ATTIVITÀ CREATIVE, ARTISTICHE E DI INTRATTENIMENTO"
  df$`ateconames`[df$`ATECO10`== "91" ] <-"ATTIVITÀ DI BIBLIOTECHE, ARCHIVI, MUSEI ED ALTRE ATTIVITÀ CULTURALI"
  df$`ateconames`[df$`ATECO10`== "92" ] <-"ATTIVITÀ RIGUARDANTI LE LOTTERIE, LE SCOMMESSE, LE CASE DA GIOCO"
  df$`ateconames`[df$`ATECO10`== "93" ] <-"ATTIVITÀ SPORTIVE, DI INTRATTENIMENTO E DI DIVERTIMENTO"
  df$`ateconames`[df$`ATECO10`== "94" ] <-"ATTIVITÀ DI ORGANIZZAZIONI ASSOCIATIVE"
  df$`ateconames`[df$`ATECO10`== "95" ] <-"RIPARAZIONE DI COMPUTER E DI BENI PER USO PERSONALE E PER LA CASA"
  df$`ateconames`[df$`ATECO10`== "96" ] <-"ALTRE ATTIVITÀ DI SERVIZI PER LA PERSONA"
  df$`ateconames`[df$`ATECO10`== "97" ] <-"ATTIVITÀ DI FAMIGLIE E CONVIVENZE COME DATORI DI LAVORO PER PERSONALE DOMESTICO"
  df$`ateconames`[df$`ATECO10`== "98" ] <-"PRODUZIONE DI BENI E SERVIZI INDIFFERENZIATI PER USO PROPRIO DA PARTE DI FAMIGLIE E CONVIVENZE"
  df$`ateconames`[df$`ATECO10`== "99" ] <-"ALTRE ATTIVITÀ DI SERVIZI PER LA PERSONA"
  
  return (df$`ateconames`)
}



getZones <- function(dfb) {
  dfb$zone[dfb$`region`== "Sicilia" ] <- "isole"
  dfb$zone[dfb$`region`== "Sardegna" ] <- "isole"
  dfb$zone[dfb$`region`== "Calabria" ] <- "sud"
  dfb$zone[dfb$`region`== "Basilicata" ] <- "sud"
  dfb$zone[dfb$`region`== "Abruzzo" ] <- "sud"
  dfb$zone[dfb$`region`== "Molise" ] <- "sud"
  dfb$zone[dfb$`region`== "Campania" ] <- "sud"
  dfb$zone[dfb$`region`== "Puglia" ] <- "sud"
  dfb$zone[dfb$`region`== "Toscana" ] <- "centro"
  dfb$zone[dfb$`region`== "Umbria" ] <- "centro"
  dfb$zone[dfb$`region`== "Marche" ] <- "centro"
  dfb$zone[dfb$`region`== "Lazio" ] <- "centro"           
  dfb$zone[dfb$`region`== "Trentino-Alto Adige" ] <- "nord est"
  dfb$zone[dfb$`region`== "Veneto" ] <- "nord est"
  dfb$zone[dfb$`region`== "Friuli-Venezia Giulia" ] <- "nord est"
  dfb$zone[dfb$`region`== "Emilia-Romagna" ] <- "nord est"
  dfb$zone[dfb$`region`== "Valle d'Aosta" ] <- "nord ovest"
  dfb$zone[dfb$`region`== "Lombardia" ] <- "nord ovest"
  dfb$zone[dfb$`region`== "Piemonte" ] <- "nord ovest"
  dfb$zone[dfb$`region`== "Liguria" ] <- "nord ovest"
  
  return(dfb$zone)
}
